### ISSUE TITLE
Error with Truffle

### ISSUE THREAD

**Issue by damianlluch** [ssteiger/Ethereum-NFT-Store-with-Dutch-Auctions#1]
Hi, thanks for sharing this resources. I have this error in your project.

/Ethereum-NFT-Store-with-Dutch-Auctions$ truffle migrate --reset --network ganache

Compiling your contracts...
===========================
Error: Error: Error: Could not find @0xcert/ethereum-utils/contracts/ownership/Ownable.sol from any sources; imported from /home/damian/Documents/tesis/prueba/Ethereum-NFT-Store-with-Dutch-Auctions/contracts/Migrations.sol
    at Object.compile (/usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-workflow-compile/index.js:103:1)
Truffle v5.0.20 (core: 5.0.20)
Node v12.3.1

**Comment by ssteiger** [comment]
I pushed a fix -> f3d9e913c95a1fb9b0f17db63f283edf6486942b.
Let me know if it is working.

**Comment by damianlluch** [comment]
Thanks for your response.
I try with your instructions but I get the same result.

**Comment by ssteiger** [comment]
Ok, I added `0xcert/ethereum-utils` as a dependency.
Any luck now? :-)

**Comment by damianlluch** [comment]
Hi Yes. I installed it manually and I have compiled and migrated it well. I'm going to test your application these days. I work with a bachelor's thesis and your project can be very helpful.
How could we do to add new numbers manually from the user panel?
I can collaborate with some personal projects that you have in exchange.

Thanks!

**Comment by ssteiger** [comment]
Cool!
If you want add new numbers manually you would first need to change the `mint()` function inside of the token contract. (https://github.com/ssteiger/Ethereum-NFT-Store-with-Dutch-Auctions/blob/master/contracts/tokens/NFTokenEnumerable.sol)
Right now a `mint` increases a counter and then creates a token with the corresponding id (counter value).
Maybe you can create an additional `map` and link some metadata to the tokens.
